name: Action CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Ejecutar mi propia action en un container
        uses: ./
        with:
          who-to-greet: '@zendejass'