# workflow to show how to develop workflows in branches
name: Develop con codigo malicios
on: [pull_request, workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: devops-actions/actionlint@v0.1.2
      - run: |
          echo "Workflow triggered in branch: '${{ github.ref }}'."
          echo "Workflow triggered by event: '${{ github.event_name }}'."
          echo "Workflow triggered by actor: '${{ github.actor }}'."
      - run: echo "PR title is '${{ github.event.pull_request.title }}'."
